//
// Created by christian on 7/3/24.
//

#ifndef WUNDER_WUNDER_RENDERER_INCLUDE_EVENT_WINDOW_EVENTS_H_
#define WUNDER_WUNDER_RENDERER_INCLUDE_EVENT_WINDOW_EVENTS_H_

struct window_close_event {

};

#endif //WUNDER_WUNDER_RENDERER_INCLUDE_EVENT_WINDOW_EVENTS_H_
